version: '3.8'

services:
  client:
    build:
      context: ./packages/run-client
      dockerfile: Dockerfile
    ports:
      - "3100:3000"
    environment:
      - VITE_API_URL=http://server:4000
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./packages/run-node
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
